flowchart TD
    Start([Start])
    Menu{Show Menu & Get User Choice}
    Add[Add Product]
    GetProductName[Prompt: Enter product name]
    SetProductName[User enters product name]
    GetProductPrice[Prompt: Enter product price]
    SetProductPrice[User enters product price]
    GetProductQty[Prompt: Enter product quantity]
    SetProductQty[User enters product quantity]
    ViewOne[View Product]
    DisplayProduct[Displays product details]
    DisplayProducts[Displays all products in inventory]
    InvalidProduct
    ViewAll[View All Products]
    Update[Update Product]
    UpdateProperty[Prompt: Select property to update for product]
    GetUpdateQty[Prompt: Enter new quantity]
    SetUpdateQty[User enters new quantity]
    UpdatedQtyMsg[Updating quantity for product]
    GetUpdatePrice[Prompt: Enter a new price]
    SetUpdatePrice[User enters a new price]
    UpdatedPriceMsg[Updating price for product]
    UpdateQty[UpdateQuantity]
    Remove["Remove Product"]
    Exit([Exit])
    Invalid[Invalid Option]

    Start --> Menu
    Menu -->|1| Add
    Add --> GetProductName --> SetProductName --> GetProductPrice --> SetProductPrice --> GetProductQty --> SetProductQty --> DisplayProduct --> Menu
    Menu -->|2| ViewOne
    ViewOne --> GetProductName --> SetProductName --> DisplayProduct --> Menu
    Menu -->|3| ViewAll
    ViewAll --> DisplayProducts --> Menu
    Menu -->|4| Update
    Update --> GetProductName --> SetProductName --> UpdateProperty
    UpdateProperty --> GetUpdateQty --> SetUpdateQty --> UpdatedQtyMsg --> Menu
    UpdateProperty --> GetUpdatePrice --> SetUpdatePrice --> UpdatedPriceMsg --> Menu
    Menu -->|5| Remove
    Menu -->|6| Exit
    Menu -->|Other| Invalid
  
    ViewOne --> Menu
    ViewAll --> Menu
    Update --> Menu
    Remove --> Menu
    Invalid --> Menu