flowchart TD
    Start([Start])
    Menu{Show Menu & Get User Choice}
    Add[Add Product]
    GetProductName[Prompt: Enter product name]
    SetProductName[User enters product name]
    GetProductPrice[Prompt: Enter product price]
    SetProductPrice[User enters product price]
    GetProductQty[Prompt: Enter product quantity]
    SetProductQty[User enters product quantity]
    DisplayAddProduct[Displays product details] 
    
    ViewOne[View Product]
    DisplayViewProduct[Displays product details]    
    GetProductViewOneName[Prompt: Enter product name]
    SetProductViewOneName[User enters product name]
    InvalidProduct{Is product valid}
    
    ViewAll[View All Products]
    InventoryEmpty{Is Inventory Empty}
    DisplayProducts[Displays all products in inventory]
    
    Update[Update Product]
    GetProductUpdateName[Prompt: Enter product name]
    SetProductUpdateName[User enters product name]
    UpdateProperty[Prompt: Select property to update for product]
    GetUpdateQty[Prompt: Enter new quantity]
    SetUpdateQty[User enters new quantity]
    UpdatedQtyMsg[Updating quantity for product]
    GetUpdatePrice[Prompt: Enter a new price]
    SetUpdatePrice[User enters a new price]
    UpdatedPriceMsg[Updating price for product]
    InvalidProductUpdate{Is product valid}

    
    Remove[Remove Product]
    GetProductRemovalName[Prompt: Enter product name]
    SetProductRemovalName[User enters product name]
    GetRemovalProduct[Prompt: Enter a product to remove]
    SetRemovalProduct[User enters a product name]
    RemovalMsg[Removing product from inventory]
    InvalidProductRemoval{Is product valid}
    
    Exit([Exit])
    Invalid[Invalid Option]

    Start --> Menu
    Menu -->|1| Add
    Add --> GetProductName --> SetProductName --> GetProductPrice --> SetProductPrice --> GetProductQty --> SetProductQty --> DisplayAddProduct --> Menu
    Menu -->|2| ViewOne
    ViewOne --> GetProductViewOneName --> SetProductViewOneName --> InvalidProduct -- Yes --> DisplayViewProduct --> Menu
    InvalidProduct -- No --> Menu
    Menu -->|3| ViewAll
    ViewAll --> InventoryEmpty -- Yes --> Menu
    InventoryEmpty -- No --> DisplayProducts --> Menu
    Menu -->|4| Update
    Update --> GetProductUpdateName --> SetProductUpdateName --> UpdateProperty
    SetProductUpdateName --> InvalidProductUpdate --> Menu
    UpdateProperty --> GetUpdateQty --> SetUpdateQty --> UpdatedQtyMsg --> Menu
    UpdateProperty --> GetUpdatePrice --> SetUpdatePrice --> UpdatedPriceMsg --> Menu
    Menu -->|5| Remove
    Remove --> GetProductRemovalName --> SetProductRemovalName --> GetRemovalProduct --> SetRemovalProduct --> RemovalMsg --> Menu
    SetProductRemovalName --> InvalidProductRemoval --> Menu
    Menu -->|6| Exit
    Menu -->|Other| Invalid
    Invalid --> Menu